name: rworkflows
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-latest
          bioc: devel
          r: devel
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          rspm: ~
        - os: macOS-latest
          bioc: devel
          r: devel
          cont: ~
          rspm: ~
        - os: windows-latest
          bioc: devel
          r: devel
          cont: ~
          rspm: ~
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies for Windows
      if: runner.os == 'Windows'
      run: |
        Rscript -e "options(repos = c(CRAN = 'https://cloud.r-project.org')); install.packages('BiocManager')"
        Rscript -e "BiocManager::install(c('GenomicRanges', 'GenomeInfoDb', 'IRanges' , 'XVector'), dependencies=TRUE, force = TRUE)"

    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: false
        run_rcmdcheck: true
        as_cran: true
        run_vignettes: true
        has_testthat: true
        run_covr: true
        run_pkgdown: true
        has_runit: false
        has_latex: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run_docker: false
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
        docker_registry: ghcr.io
