name: rworkflows
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-latest
          bioc: devel
          r: devel
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          rspm: ~
        - os: macOS-latest
          bioc: devel
          r: devel
          cont: ~
          rspm: ~
        - os: windows-latest
          bioc: devel
          r: devel
          cont: ~
          rspm: ~
    steps:
    - uses: actions/checkout@v3

    # Install dependencies specifically on Windows
    - name: Install R and Bioconductor dependencies
      if: runner.os == 'Windows'
      run: |
        Rscript -e "options(repos = c(CRAN = 'https://cloud.r-project.org')); install.packages('BiocManager')"
        Rscript -e "lib_path <- .libPaths()[1]; BiocManager::install(c('GenomicRanges', 'GenomeInfoDb', 'IRanges', 'XVector'), lib = lib_path, dependencies = TRUE, force = TRUE)"

    # Add the R library path to the environment for subsequent steps
    - name: Set R library path
      if: runner.os == 'Windows'
      run: echo "R_LIBS_USER=$(Rscript -e 'cat(.libPaths()[1])')" >> $GITHUB_ENV

    # Run neurogenomics/rworkflows
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: false
        run_rcmdcheck: true
        as_cran: true
        run_vignettes: false
        has_testthat: true
        run_covr: true
        run_pkgdown: true
        has_runit: false
        has_latex: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run_docker: false
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
        docker_registry: ghcr.io
